# Generated by Django 4.2.17 on 2025-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_bayer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
